server:
  servlet:
    port: 8080
    context-path: /v1

spring:
  application:
    name: prime-numbers

prime:
  cache:
    name: primeNumberCache
    maxentries: 250
    eviction:
      policy: LRU
    persistence:
      strategy: LOCALTEMPSWAP
    time:
      to:
        idle:
          sec: 300
        live:
          sec: 900